---
pages:
- _products/squid-invader-hat.md
hide_body: false
fields:
- type: text
  name: layout
  label: Layout
  description: The layout of the page
  hidden: ''
  config:
    required: true
  default: product
- type: text
  label: ID
  name: product_id
  description: The product id
